#!/bin/bash

# Scripts for helping with Blockly++ development.
# Run envsetup.sh to set the path for this script, then
# use the commands with bgit <command>

function start {
  if [ "$1" != "" ]; then
    git checkout -b $1 master
  else
    echo "Usage: bgit start <branch name>"
  fi
}

function close {
  if [ "$BLOCKLY_INIT" != true ]; then
    echo "Must run envsetup.sh before closing a branch!"
    return
  fi

  local branch="$(git rev-parse --abbrev-ref HEAD)"
  if [ "$branch" = "master" ]; then
    echo "Cannot close the master branch"
    return
  fi

  while true; do
    read -p "This will delete the remote and local branches for $branch. Continue? (y/n):" yn
    case $yn in
      [Yy]* ) break;;
      [Nn]* ) return;;
      * ) echo "Please type y or n";;
    esac
  done
  rem_branch="$BLOCKLY_USER-$branch"
  git push origin :$rem_branch
  git checkout master
  git branch -D $branch
}

function run_tests_android() {
  local verbose=""
  while [ "$1" != "" ]; do
    case $1 in
      -v | --verbose ) verbose="true";;
      * )             echo "unknown arg $1";;
    esac
    shift
  done

  local args=""
  if test -z $verbose; then
    args="-q"
  fi

  echo -n "Running tests... "

  pushd android/Blockly/ >& /dev/null

  if ! ./gradlew $args cC; then
    echo "FAILED - ABORTING"
    popd >& /dev/null
    exit 1
  fi

  echo "SUCCESS"
  popd >& /dev/null
}

function run_tests() {
  if [ $(uname) == "Linux" ]; then
    run_tests_android $*
  else
    echo "Tests not yet supported on this platform."
  fi
}

function push {
  if [ "$BLOCKLY_INIT" != true ]; then
    echo "Must run envsetup.sh before pushing commits!"
    return
  fi

  local args=""

  while [ "$1" != "" ]; do
    case $1 in
      -f | --force )  args="$args $1";;
      * )             echo "unknown arg $1";;
    esac
    shift
  done

  run_tests

  local branch="$(git rev-parse --abbrev-ref HEAD)"
  local rem_branch="$BLOCKLY_USER-$branch"
  git push$args origin "$branch:$rem_branch"
  echo "Pushed change to $rem_branch. Add a reviewer on the website."
}

#NOTE: pull will only work after you've created the branch with push
function pull {
  if [ "$BLOCKLY_INIT" != true ]; then
    echo "Must run envsetup.sh before pulling!"
    return
  fi
  local branch="$(git rev-parse --abbrev-ref HEAD)"
  local rem_branch=""
  if [ "$branch" = "master" ]; then
    rem_branch="master"
  else
    rem_branch="$BLOCKLY_USER-$branch"
  fi
  git pull origin $rem_branch
}

#Rebase the current branch on to master
function rebase {
  git pull origin master:master
  # Get the current branch name
  local branch="$(git rev-parse --abbrev-ref HEAD)"
  # Get the base CL where our local changes diverged from master
  local cl="$(git merge-base $branch master)"
  local args=""

  while [ "$1" != "" ]; do
    case $1 in
      -i | --interactive )  args="$args $1";;
      * )                   echo "unknown arg $1";;
    esac
    shift
  done

  echo "Rebasing onto $cl with args $args"
  git rebase$args $cl
}

function help {
  echo "Available commands are:"
  echo "bgit start <branch> # Start a new local branch."
  echo "bgit close # Delete the current branch on GitHub and locally"
  echo "bgit push # Push the current branch to GitHub. Creates a remote branch if needed."
  echo "bgit pull # Pull any changes to the current branch from GitHub"
  echo "bgit rebase # Rebase your current branch on to master"
}

if [ "$1" = "" ]; then
  help
else
  command=$1
  shift
  case $command in
    start )   start $@;;
    close )   close $@;;
    push )    push $@;;
    pull )    pull $@;;
    rebase )  rebase $@;;
    test)     run_tests $@;;
    *)        help;;
  esac
fi
